base_images:
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openshift_release_golang-1.18:
    name: release
    namespace: openshift
    tag: golang-1.18
binary_build_commands: "echo \"no build commands\" \n"
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- dockerfile_literal: |
    FROM registry.fedoraproject.org/fedora:36
    RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
    RUN mkdir -p /usr/local/gcloud \
      && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
      && /usr/local/gcloud/google-cloud-sdk/install.sh \
      && rm -f /tmp/google-cloud-sdk.tar.gz
    ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
    WORKDIR /src
    COPY . .
  from: src
  to: crio-crio-base-src
releases:
  initial:
    integration:
      name: "4.10"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.10"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: "echo \"no test commands\" \n"
tests:
- as: rhel-e2e
  steps:
    cluster_profile: gcp
    workflow: rhel-cri-o-e2e
- as: rhel-integration
  steps:
    cluster_profile: gcp
    workflow: rhel-cri-o-integration
- as: rhel-critest
  steps:
    cluster_profile: gcp
    workflow: rhel-cri-o-critest
# - as: fedora-e2e
#   steps:
#     cluster_profile: gcp
#     workflow: fedora-cri-o-e2e
# - as: fedora-integration
#   steps:
#     cluster_profile: gcp
#     workflow: fedora-cri-o-integration
# - as: fedora-critest
#   steps:
#     cluster_profile: gcp
#     workflow: fedora-cri-o-critest
# - as: crun-e2e
#   steps:
#     cluster_profile: gcp
#     workflow: crun-cri-o-e2e
# - as: crun-integration
#   steps:
#     cluster_profile: gcp
#     workflow: crun-cri-o-integration
# - as: cgroupsv2-e2e
#   steps:
#     cluster_profile: gcp
#     workflow: cri-o-e2e
# - as: cgroupsv2-integration-crun
#   steps:
#     cluster_profile: gcp
#     workflow: cgroupsv2-cri-o-integration
# - as: cgroupsv2-e2e-crun
#   steps:
#     cluster_profile: gcp
#     workflow: cgroupsv2-cri-o-e2e-crun
zz_generated_metadata:
  branch: ci-v2
  org: cri-o
  repo: cri-o
